### ISSUE TITLE
Font appears too big

### ISSUE THREAD

**Issue by eoinbutler** [palfrey/postcode#6]
With the latest update, the font is so big, only the first letter can fit on the screen.

**Comment by palfrey** [comment]
Huh. I didn't think I'd actually made any real changes (other than updating the API version). Right, will have a look at that...

**Comment by palfrey** [comment]
I've just pushed out a new release that I think fixes this (changes is just 20f9aa89d066901eafd9ad88edaa11396e92f40d), but please let me know.

**Comment by eoinbutler** [comment]
Seems to work for me now. Thanks very much!
